//
//  App_StyleKit.h
//  App_UI
//
//  Created by Eric Swinson on 2/27/15.
//  Copyright (c) 2015 Seequ. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface App_StyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* seequ_Splash_LogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_6_Plus_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_6_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_5_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_4_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* login_logoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* login_footer_logoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* login_text_field_backgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_profile_photo_placeholderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_profile_photo_frameTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_footer_logoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* contact_profile_photo_placeholderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* contact_slide_arrowTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* contact_invite_userTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_navigationBarTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_url_field_backgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_url_reload_buttonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_url_cancel_buttonTargets;

// Colors
+ (UIColor*)seequFoam;
+ (UIColor*)seequFoam_50;
+ (UIColor*)seequFoam_Dark;
+ (UIColor*)black;
+ (UIColor*)black_50;
+ (UIColor*)white;
+ (UIColor*)white_25_Percent;
+ (UIColor*)active_Call_Green;
+ (UIColor*)error_Border;
+ (UIColor*)red_15;
+ (UIColor*)frame_Color;
+ (UIColor*)away_Yellow;
+ (UIColor*)group_Purple;

// Gradients
+ (PCGradient*)splash_Gradient;

// Drawing Methods
+ (void)drawSeequ_Splash_Logo;
+ (void)drawIPhone_6_Plus_Splash;
+ (void)drawIPhone_6_Splash;
+ (void)drawIPhone_5_Splash;
+ (void)drawIPhone_4_Splash;
+ (void)drawLogin_logo;
+ (void)drawLogin_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_create_account_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_create_forgot_password_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_footer_logo;
+ (void)drawLogin_text_field_background;
+ (void)drawResizable_text_field_backgroundWithFrame: (CGRect)frame error: (BOOL)error;
+ (void)drawRegistration_profile_photo_placeholder;
+ (void)drawRegistration_profile_photo_frame;
+ (void)drawRegistration_footer_logo;
+ (void)drawRegistration_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (void)drawRegistration_footer_create_account_buttonWithPressed: (BOOL)pressed;
+ (void)drawNotification_badgeWithNotifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_contactsWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_messagesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_browserWithPressed: (BOOL)pressed notifications: (CGFloat)notifications buddybrowse: (BOOL)buddybrowse;
+ (void)drawTab_bar_icon_activityWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_takesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawConatct_row_seequWithFrame: (CGRect)frame frame2: (CGRect)frame2 frame3: (CGRect)frame3 frame4: (CGRect)frame4 notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company;
+ (void)drawContact_profile_photo_placeholder;
+ (void)drawContact_status_ringWithAway: (BOOL)away;
+ (void)drawContact_slide_arrow;
+ (void)drawConatct_row_phoneWithFrame2: (CGRect)frame2 frame3: (CGRect)frame3 firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company;
+ (void)drawConatct_row_phone_drawer;
+ (void)drawContact_invite_user;
+ (void)drawConatct_row_seequ_drawer;
+ (void)drawContact_call_icon;
+ (void)drawContact_messenger_iconWithPressed: (BOOL)pressed;
+ (void)drawContact_status_ring_busyWithBusy: (BOOL)busy;
+ (void)drawContact_status_ring_awayWithAway: (BOOL)away;
+ (void)drawContact_status_ring_availableWithOnline: (BOOL)online;
+ (void)drawContact_status_ring_groupWithContactgroup: (BOOL)contactgroup;
+ (void)drawLogin_progress_graphWithProgressPercent: (CGFloat)progressPercent;
+ (void)drawTerms_of_service_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (void)drawTerms_of_service_footer_agree_buttonWithPressed: (BOOL)pressed;
+ (void)drawBrowser_navigationBar;
+ (void)drawBrowser_url_field_background;
+ (void)drawBrowser_url_reload_button;
+ (void)drawBrowser_url_cancel_button;
+ (void)drawBrowser_next_arrowWithPressed: (BOOL)pressed active: (BOOL)active;
+ (void)drawBrowser_prev_arrowWithPressed: (BOOL)pressed active: (BOOL)active;
+ (void)drawBrowser_buddy_browser_buttonWithBuddybrowse: (BOOL)buddybrowse;
+ (void)drawBrowser_share_menu_buttonWithPressed: (BOOL)pressed;
+ (void)drawBrowser_bookmark_buttonWithPressed: (BOOL)pressed;

// Generated Images
+ (UIImage*)imageOfSeequ_Splash_Logo;
+ (UIImage*)imageOfIPhone_6_Plus_Splash;
+ (UIImage*)imageOfIPhone_6_Splash;
+ (UIImage*)imageOfIPhone_5_Splash;
+ (UIImage*)imageOfIPhone_4_Splash;
+ (UIImage*)imageOfLogin_logo;
+ (UIImage*)imageOfLogin_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_create_account_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_create_forgot_password_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_footer_logo;
+ (UIImage*)imageOfLogin_text_field_background;
+ (UIImage*)imageOfResizable_text_field_backgroundWithFrame: (CGRect)frame error: (BOOL)error;
+ (UIImage*)imageOfRegistration_profile_photo_placeholder;
+ (UIImage*)imageOfRegistration_profile_photo_frame;
+ (UIImage*)imageOfRegistration_footer_logo;
+ (UIImage*)imageOfRegistration_footer_create_account_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfNotification_badgeWithNotifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_contactsWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_messagesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_browserWithPressed: (BOOL)pressed notifications: (CGFloat)notifications buddybrowse: (BOOL)buddybrowse;
+ (UIImage*)imageOfTab_bar_icon_activityWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_takesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfConatct_row_seequWithFrame: (CGRect)frame frame2: (CGRect)frame2 frame3: (CGRect)frame3 frame4: (CGRect)frame4 notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company;
+ (UIImage*)imageOfContact_profile_photo_placeholder;
+ (UIImage*)imageOfContact_status_ringWithAway: (BOOL)away;
+ (UIImage*)imageOfContact_slide_arrow;
+ (UIImage*)imageOfConatct_row_phoneWithFrame2: (CGRect)frame2 frame3: (CGRect)frame3 firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company;
+ (UIImage*)imageOfContact_invite_user;
+ (UIImage*)imageOfContact_status_ring_busyWithBusy: (BOOL)busy;
+ (UIImage*)imageOfContact_status_ring_awayWithAway: (BOOL)away;
+ (UIImage*)imageOfContact_status_ring_groupWithContactgroup: (BOOL)contactgroup;
+ (UIImage*)imageOfLogin_progress_graphWithProgressPercent: (CGFloat)progressPercent;
+ (UIImage*)imageOfTerms_of_service_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfTerms_of_service_footer_agree_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfBrowser_navigationBar;
+ (UIImage*)imageOfBrowser_url_field_background;
+ (UIImage*)imageOfBrowser_url_reload_button;
+ (UIImage*)imageOfBrowser_url_cancel_button;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
