//
//  App_StyleKit.h
//  App_UI
//
//  Created by Eric Swinson on 3/11/15.
//  Copyright (c) 2015 Seequ. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface RingStyleKit : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* seequ_Splash_LogoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_6_Plus_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_6_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_5_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* iPhone_4_SplashTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* login_footer_logoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* login_text_field_backgroundTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_profile_photo_placeholderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_profile_photo_frameTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* registration_footer_logoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* contact_profile_photo_placeholderTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* contact_invite_userTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_navigationBarTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* browser_url_cancel_buttonTargets;

// Colors
+ (UIColor*)seequFoam;
+ (UIColor*)seequFoam_50;
+ (UIColor*)seequFoam_Dark;
+ (UIColor*)black;
+ (UIColor*)black_50;
+ (UIColor*)white;
+ (UIColor*)white_25_Percent;
+ (UIColor*)active_Call_Green;
+ (UIColor*)error_Border;
+ (UIColor*)red_15;
+ (UIColor*)frame_Color;
+ (UIColor*)away_Yellow;
+ (UIColor*)group_Purple;

// Gradients
+ (PCGradient*)splash_Gradient;

// Drawing Methods
+ (void)drawSeequ_Splash_Logo;
+ (void)drawIPhone_6_Plus_Splash;
+ (void)drawIPhone_6_Splash;
+ (void)drawIPhone_5_Splash;
+ (void)drawIPhone_4_Splash;
+ (void)drawLogin_logoWithProgressPercent: (CGFloat)progressPercent;
+ (void)drawLogin_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_create_account_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_create_forgot_password_buttonWithPressed: (BOOL)pressed;
+ (void)drawLogin_footer_logo;
+ (void)drawLogin_text_field_background;
+ (void)drawResizable_text_field_backgroundWithFrame: (CGRect)frame error: (BOOL)error;
+ (void)drawRegistration_profile_photo_placeholder;
+ (void)drawRegistration_profile_photo_frame;
+ (void)drawRegistration_footer_logo;
+ (void)drawRegistration_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (void)drawRegistration_footer_create_account_buttonWithPressed: (BOOL)pressed;
+ (void)drawNotification_badgeWithNotifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_contactsWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_messagesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_browserWithPressed: (BOOL)pressed notifications: (CGFloat)notifications buddybrowse: (BOOL)buddybrowse;
+ (void)drawTab_bar_icon_activityWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawTab_bar_icon_takesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (void)drawContact_rowWithFrame: (CGRect)frame contact_row_frame: (CGRect)contact_row_frame contact_profile_placeholder: (UIImage*)contact_profile_placeholder notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company favorite: (BOOL)favorite;
+ (void)drawContact_profile_photo_placeholder;
+ (void)drawContact_status_ringWithAway: (BOOL)away contactgroup: (BOOL)contactgroup busy: (BOOL)busy active: (BOOL)active unknown: (BOOL)unknown;
+ (void)drawContact_slide_arrowWithOpened: (BOOL)opened;
+ (void)drawConatct_row_phone_drawer;
+ (void)drawContact_invite_user;
+ (void)drawConatct_row_seequ_drawer;
+ (void)drawContact_call_icon;
+ (void)drawContact_messenger_iconWithPressed: (BOOL)pressed;
+ (void)drawContact_alpha_seperatorWithAlpha_string: (NSString*)alpha_string;
+ (void)drawConatct_row_group_drawer;
+ (void)drawActivity_rowWithFrame: (CGRect)frame activity_row_frame: (CGRect)activity_row_frame contact_profile_placeholder: (UIImage*)contact_profile_placeholder pressed: (BOOL)pressed notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName favorite: (BOOL)favorite timestamp_text: (NSString*)timestamp_text;
+ (void)drawAndroidautorenew512px;
+ (void)drawCanvas1426121214_672366x;
+ (void)drawCanvas1426121214_672366x2;
+ (void)drawLogin_progress_graphWithProgressPercent: (CGFloat)progressPercent;
+ (void)drawTerms_of_service_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (void)drawTerms_of_service_footer_agree_buttonWithPressed: (BOOL)pressed;
+ (void)drawBrowser_navigationBar;
+ (void)drawBrowser_url_field_backgroundWithFrame: (CGRect)frame;
+ (void)drawBrowser_url_reload_buttonWithPressed: (BOOL)pressed;
+ (void)drawBrowser_url_cancel_button;
+ (void)drawBrowser_next_arrowWithPressed: (BOOL)pressed active: (BOOL)active;
+ (void)drawBrowser_prev_arrowWithPressed: (BOOL)pressed active: (BOOL)active;
+ (void)drawBrowser_buddy_browser_buttonWithPressed: (BOOL)pressed buddybrowse: (BOOL)buddybrowse;
+ (void)drawBrowser_share_menu_buttonWithPressed: (BOOL)pressed;
+ (void)drawBrowser_bookmark_buttonWithPressed: (BOOL)pressed;
+ (void)drawCanvas1;
+ (void)drawNotification_modalWithNotification_text: (NSString*)notification_text notification_subtext: (NSString*)notification_subtext;
+ (void)drawCanvas2;

// Generated Images
+ (UIImage*)imageOfSeequ_Splash_Logo;
+ (UIImage*)imageOfIPhone_6_Plus_Splash;
+ (UIImage*)imageOfIPhone_6_Splash;
+ (UIImage*)imageOfIPhone_5_Splash;
+ (UIImage*)imageOfIPhone_4_Splash;
+ (UIImage*)imageOfLogin_logoWithProgressPercent: (CGFloat)progressPercent;
+ (UIImage*)imageOfLogin_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_create_account_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_create_forgot_password_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfLogin_footer_logo;
+ (UIImage*)imageOfLogin_text_field_background;
+ (UIImage*)imageOfResizable_text_field_backgroundWithFrame: (CGRect)frame error: (BOOL)error;
+ (UIImage*)imageOfRegistration_profile_photo_placeholder;
+ (UIImage*)imageOfRegistration_profile_photo_frame;
+ (UIImage*)imageOfRegistration_footer_logo;
+ (UIImage*)imageOfRegistration_footer_create_account_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfNotification_badgeWithNotifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_contactsWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_messagesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_browserWithPressed: (BOOL)pressed notifications: (CGFloat)notifications buddybrowse: (BOOL)buddybrowse;
+ (UIImage*)imageOfTab_bar_icon_activityWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfTab_bar_icon_takesWithPressed: (BOOL)pressed notifications: (CGFloat)notifications;
+ (UIImage*)imageOfContact_rowWithFrame: (CGRect)frame contact_row_frame: (CGRect)contact_row_frame contact_profile_placeholder: (UIImage*)contact_profile_placeholder notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName title: (NSString*)title company: (NSString*)company favorite: (BOOL)favorite;
+ (UIImage*)imageOfContact_profile_photo_placeholder;
+ (UIImage*)imageOfContact_status_ringWithAway: (BOOL)away contactgroup: (BOOL)contactgroup busy: (BOOL)busy active: (BOOL)active unknown: (BOOL)unknown;
+ (UIImage*)imageOfContact_slide_arrowWithOpened: (BOOL)opened;
+ (UIImage*)imageOfContact_invite_user;
+ (UIImage*)imageOfActivity_rowWithFrame: (CGRect)frame activity_row_frame: (CGRect)activity_row_frame contact_profile_placeholder: (UIImage*)contact_profile_placeholder pressed: (BOOL)pressed notifications: (CGFloat)notifications firstName: (NSString*)firstName lastName: (NSString*)lastName favorite: (BOOL)favorite timestamp_text: (NSString*)timestamp_text;
+ (UIImage*)imageOfLogin_progress_graphWithProgressPercent: (CGFloat)progressPercent;
+ (UIImage*)imageOfTerms_of_service_footer_cancel_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfTerms_of_service_footer_agree_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfBrowser_navigationBar;
+ (UIImage*)imageOfBrowser_url_field_backgroundWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBrowser_url_reload_buttonWithPressed: (BOOL)pressed;
+ (UIImage*)imageOfBrowser_url_cancel_button;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end



@interface UIColor (PaintCodeAdditions)

- (UIColor*)blendedColorWithFraction: (CGFloat)fraction ofColor: (UIColor*)color;

@end
